
--[[------------------------------------------------------------------------------
-- <auto-generated>
--     This code was generated by a tool.
--     Changes to this file may cause incorrect behavior and will be lost if
--     the code is regenerated.
-- </auto-generated>
--]]------------------------------------------------------------------------------

local setmetatable = setmetatable
local pairs = pairs
local tinsert = table.insert

local function get_map_size(m)
    local n = 0
    for _ in pairs(m) do
        n = n + 1
    end
    return n
end

local enums =
{
}

local tables =
{
    { name='CharacterConfigTable', file='constructor_characterconfigtable', mode='map', index='id', value_type='constructor.CharacterConfig' },
    { name='ItemTable', file='examples_itemtable', mode='map', index='id', value_type='examples.Item' },
    { name='SkillTable', file='examples_skilltable', mode='map', index='id', value_type='examples.Skill' },
    { name='MonsterTable', file='examples_monstertable', mode='map', index='id', value_type='examples.Monster' },
    { name='PlayerTable', file='examples_playertable', mode='map', index='id', value_type='examples.Player' },
    { name='DifficultyTable', file='examples_difficultytable', mode='map', index='id', value_type='examples.Difficulty' },
    { name='TeamTable', file='examples_teamtable', mode='map', index='id', value_type='examples.Team' },
    { name='PoisonEffectTable', file='implements_parent_poisoneffecttable', mode='map', index='id', value_type='implements_parent.PoisonEffect' },
    { name='BuffEffectTable', file='implements_parent_buffeffecttable', mode='map', index='id', value_type='implements_parent.BuffEffect' },
    { name='WeaponTable', file='items_weapontable', mode='map', index='id', value_type='items.Weapon' },
    { name='ArmorTable', file='items_armortable', mode='map', index='id', value_type='items.Armor' },
    { name='LeaderboardEntryTable', file='modes_leaderboardentrytable', mode='list', index='rank', value_type='modes.LeaderboardEntry' },
    { name='GameConfigTable', file='modes_gameconfigtable', mode='one', value_type='modes.GameConfig'},
    { name='ServerSettingsTable', file='modes_serversettingstable', mode='one', value_type='modes.ServerSettings'},
    { name='WeaponConfigTable', file='virtual_fields_weaponconfigtable', mode='map', index='id', value_type='virtual_fields.WeaponConfig' },
    { name='ArmorConfigTable', file='virtual_fields_armorconfigtable', mode='map', index='id', value_type='virtual_fields.ArmorConfig' },
}

local function InitTypes(methods)
    local readList = methods.readList
    local readArray = methods.readArray or readList
    local readSet = methods.readSet
    local readMap = methods.readMap

    local beans = {}
    do
        local class = methods.getClass('field_visibility.ITestInterface')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            setmetatable(o, class)
            return o
        end
        beans['field_visibility.ITestInterface'] = class
    end
    do
        local class = methods.getClass('implements_parent.IEntity')
        class._deserialize = function(bs)
            local __type__ = bs["$type"]
if __type__ == "implements_parent.HealEffect" then
                return beans["implements_parent.HealEffect"]._deserialize(bs)
elseif __type__ == "implements_parent.BuffEffect" then
                return beans["implements_parent.BuffEffect"]._deserialize(bs)
elseif __type__ == "implements_parent.FireEffect" then
                return beans["implements_parent.FireEffect"]._deserialize(bs)
            else
                error("Unknown type for implements_parent.IEntity: " .. tostring(__type__))
            end
        end
        beans['implements_parent.IEntity'] = class
    end
    do
        local class = methods.getClass('implements_parent.FireEffect')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            setmetatable(o, class)
            return o
        end
        beans['implements_parent.FireEffect'] = class
    end
    do
        local class = methods.getClass('implements_parent.IEffect')
        class._deserialize = function(bs)
            local __type__ = bs["$type"]
if __type__ == "implements_parent.HealEffect" then
                return beans["implements_parent.HealEffect"]._deserialize(bs)
elseif __type__ == "implements_parent.BuffEffect" then
                return beans["implements_parent.BuffEffect"]._deserialize(bs)
            else
                error("Unknown type for implements_parent.IEffect: " .. tostring(__type__))
            end
        end
        beans['implements_parent.IEffect'] = class
    end
    do
        local class = methods.getClass('implements_parent.HealEffect')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            setmetatable(o, class)
            return o
        end
        beans['implements_parent.HealEffect'] = class
    end
    do
        local class = methods.getClass('implements_parent.PoisonEffect')
        class._deserialize = function(bs)
            local __type__ = bs["$type"]
if __type__ == "implements_parent.BuffEffect" then
                return beans["implements_parent.BuffEffect"]._deserialize(bs)
            else
                error("Unknown type for implements_parent.PoisonEffect: " .. tostring(__type__))
            end
        end
        beans['implements_parent.PoisonEffect'] = class
    end
    do
        local class = methods.getClass('implements_parent.BuffEffect')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            setmetatable(o, class)
            return o
        end
        beans['implements_parent.BuffEffect'] = class
    end
    do
        local class = methods.getClass('TsClass')
        class._deserialize = function(bs)
            local __type__ = bs["$type"]
if __type__ == "constructor.DamageTrigger" then
                return beans["constructor.DamageTrigger"]._deserialize(bs)
elseif __type__ == "constructor.HealTrigger" then
                return beans["constructor.HealTrigger"]._deserialize(bs)
elseif __type__ == "constructor.CharacterConfig" then
                return beans["constructor.CharacterConfig"]._deserialize(bs)
elseif __type__ == "examples.Item" then
                return beans["examples.Item"]._deserialize(bs)
elseif __type__ == "examples.Skill" then
                return beans["examples.Skill"]._deserialize(bs)
elseif __type__ == "examples.DropItem" then
                return beans["examples.DropItem"]._deserialize(bs)
elseif __type__ == "examples.Monster" then
                return beans["examples.Monster"]._deserialize(bs)
elseif __type__ == "examples.Player" then
                return beans["examples.Player"]._deserialize(bs)
elseif __type__ == "examples.Difficulty" then
                return beans["examples.Difficulty"]._deserialize(bs)
elseif __type__ == "examples.Team" then
                return beans["examples.Team"]._deserialize(bs)
elseif __type__ == "field_visibility.TestPrivateFields" then
                return beans["field_visibility.TestPrivateFields"]._deserialize(bs)
elseif __type__ == "field_visibility.TestReadonlyFields" then
                return beans["field_visibility.TestReadonlyFields"]._deserialize(bs)
elseif __type__ == "implements_parent.MultiInterfaceEffect" then
                return beans["implements_parent.MultiInterfaceEffect"]._deserialize(bs)
elseif __type__ == "implements_parent.StandaloneClass" then
                return beans["implements_parent.StandaloneClass"]._deserialize(bs)
elseif __type__ == "inheritance.PlayerUnit" then
                return beans["inheritance.PlayerUnit"]._deserialize(bs)
elseif __type__ == "inheritance.NPCUnit" then
                return beans["inheritance.NPCUnit"]._deserialize(bs)
elseif __type__ == "inheritance.StandaloneUnit" then
                return beans["inheritance.StandaloneUnit"]._deserialize(bs)
elseif __type__ == "items.Weapon" then
                return beans["items.Weapon"]._deserialize(bs)
elseif __type__ == "items.Armor" then
                return beans["items.Armor"]._deserialize(bs)
elseif __type__ == "items.EquipmentSet" then
                return beans["items.EquipmentSet"]._deserialize(bs)
elseif __type__ == "modes.LeaderboardEntry" then
                return beans["modes.LeaderboardEntry"]._deserialize(bs)
elseif __type__ == "modes.GameConfig" then
                return beans["modes.GameConfig"]._deserialize(bs)
elseif __type__ == "modes.ServerSettings" then
                return beans["modes.ServerSettings"]._deserialize(bs)
elseif __type__ == "virtual_fields.ScalingStat" then
                return beans["virtual_fields.ScalingStat"]._deserialize(bs)
elseif __type__ == "virtual_fields.WeaponConfig" then
                return beans["virtual_fields.WeaponConfig"]._deserialize(bs)
elseif __type__ == "virtual_fields.ArmorConfig" then
                return beans["virtual_fields.ArmorConfig"]._deserialize(bs)
            else
                error("Unknown type for TsClass: " .. tostring(__type__))
            end
        end
        beans['TsClass'] = class
    end
    do
        local class = methods.getClass('constructor.BaseTrigger')
        class._deserialize = function(bs)
            local __type__ = bs["$type"]
if __type__ == "constructor.DamageTrigger" then
                return beans["constructor.DamageTrigger"]._deserialize(bs)
elseif __type__ == "constructor.HealTrigger" then
                return beans["constructor.HealTrigger"]._deserialize(bs)
            else
                error("Unknown type for constructor.BaseTrigger: " .. tostring(__type__))
            end
        end
        beans['constructor.BaseTrigger'] = class
    end
    do
        local class = methods.getClass('constructor.DamageTrigger')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            setmetatable(o, class)
            return o
        end
        beans['constructor.DamageTrigger'] = class
    end
    do
        local class = methods.getClass('constructor.HealTrigger')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            setmetatable(o, class)
            return o
        end
        beans['constructor.HealTrigger'] = class
    end
    do
        local class = methods.getClass('constructor.CharacterConfig')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            o.triggerType = methods.getClass(bs.triggerType)
            setmetatable(o, class)
            return o
        end
        beans['constructor.CharacterConfig'] = class
    end
    do
        local class = methods.getClass('examples.Difficulty')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            setmetatable(o, class)
            return o
        end
        beans['examples.Difficulty'] = class
    end
    do
        local class = methods.getClass('examples.DropItem')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            setmetatable(o, class)
            return o
        end
        beans['examples.DropItem'] = class
    end
    do
        local class = methods.getClass('examples.Item')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            setmetatable(o, class)
            return o
        end
        beans['examples.Item'] = class
    end
    do
        local class = methods.getClass('examples.Monster')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            o.drops = readList(bs.drops, beans['examples.DropItem']._deserialize)
            setmetatable(o, class)
            return o
        end
        beans['examples.Monster'] = class
    end
    do
        local class = methods.getClass('examples.Player')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            setmetatable(o, class)
            return o
        end
        beans['examples.Player'] = class
    end
    do
        local class = methods.getClass('examples.Skill')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            setmetatable(o, class)
            return o
        end
        beans['examples.Skill'] = class
    end
    do
        local class = methods.getClass('examples.Team')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            setmetatable(o, class)
            return o
        end
        beans['examples.Team'] = class
    end
    do
        local class = methods.getClass('field_visibility.TestPrivateFields')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            setmetatable(o, class)
            return o
        end
        beans['field_visibility.TestPrivateFields'] = class
    end
    do
        local class = methods.getClass('field_visibility.TestReadonlyFields')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            setmetatable(o, class)
            return o
        end
        beans['field_visibility.TestReadonlyFields'] = class
    end
    do
        local class = methods.getClass('implements_parent.MultiInterfaceEffect')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            setmetatable(o, class)
            return o
        end
        beans['implements_parent.MultiInterfaceEffect'] = class
    end
    do
        local class = methods.getClass('implements_parent.StandaloneClass')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            setmetatable(o, class)
            return o
        end
        beans['implements_parent.StandaloneClass'] = class
    end
    do
        local class = methods.getClass('inheritance.BaseUnit')
        class._deserialize = function(bs)
            local __type__ = bs["$type"]
if __type__ == "inheritance.PlayerUnit" then
                return beans["inheritance.PlayerUnit"]._deserialize(bs)
elseif __type__ == "inheritance.NPCUnit" then
                return beans["inheritance.NPCUnit"]._deserialize(bs)
            else
                error("Unknown type for inheritance.BaseUnit: " .. tostring(__type__))
            end
        end
        beans['inheritance.BaseUnit'] = class
    end
    do
        local class = methods.getClass('inheritance.CharacterUnit')
        class._deserialize = function(bs)
            local __type__ = bs["$type"]
if __type__ == "inheritance.PlayerUnit" then
                return beans["inheritance.PlayerUnit"]._deserialize(bs)
elseif __type__ == "inheritance.NPCUnit" then
                return beans["inheritance.NPCUnit"]._deserialize(bs)
            else
                error("Unknown type for inheritance.CharacterUnit: " .. tostring(__type__))
            end
        end
        beans['inheritance.CharacterUnit'] = class
    end
    do
        local class = methods.getClass('inheritance.NPCUnit')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            setmetatable(o, class)
            return o
        end
        beans['inheritance.NPCUnit'] = class
    end
    do
        local class = methods.getClass('inheritance.PlayerUnit')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            setmetatable(o, class)
            return o
        end
        beans['inheritance.PlayerUnit'] = class
    end
    do
        local class = methods.getClass('inheritance.StandaloneUnit')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            setmetatable(o, class)
            return o
        end
        beans['inheritance.StandaloneUnit'] = class
    end
    do
        local class = methods.getClass('items.Armor')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            setmetatable(o, class)
            return o
        end
        beans['items.Armor'] = class
    end
    do
        local class = methods.getClass('items.EquipmentSet')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            setmetatable(o, class)
            return o
        end
        beans['items.EquipmentSet'] = class
    end
    do
        local class = methods.getClass('items.Weapon')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            setmetatable(o, class)
            return o
        end
        beans['items.Weapon'] = class
    end
    do
        local class = methods.getClass('modes.GameConfig')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            setmetatable(o, class)
            return o
        end
        beans['modes.GameConfig'] = class
    end
    do
        local class = methods.getClass('modes.LeaderboardEntry')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            setmetatable(o, class)
            return o
        end
        beans['modes.LeaderboardEntry'] = class
    end
    do
        local class = methods.getClass('modes.ServerSettings')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            setmetatable(o, class)
            return o
        end
        beans['modes.ServerSettings'] = class
    end
    do
        local class = methods.getClass('virtual_fields.ArmorConfig')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            o.defenseStat = beans['virtual_fields.ScalingStat']._deserialize(bs.defenseStat)
            setmetatable(o, class)
            return o
        end
        beans['virtual_fields.ArmorConfig'] = class
    end
    do
        local class = methods.getClass('virtual_fields.ScalingStat')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            setmetatable(o, class)
            return o
        end
        beans['virtual_fields.ScalingStat'] = class
    end
    do
        local class = methods.getClass('virtual_fields.WeaponConfig')
        class._deserialize = function(bs)
            local o = table.clone(bs)
            o.mainStat = beans['virtual_fields.ScalingStat']._deserialize(bs.mainStat)
            o.subStat = beans['virtual_fields.ScalingStat']._deserialize(bs.subStat)
            setmetatable(o, class)
            return o
        end
        beans['virtual_fields.WeaponConfig'] = class
    end


    return { enums = enums, beans = beans, tables = tables }
    end

return { InitTypes = InitTypes }


