
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



import type { AttributeType } from "../enums/attribute-type";
import {  } from "../enums/attribute-type";
import type { QualityType } from "../enums/quality-type";
import {  } from "../enums/quality-type";
import type { ResourceConfig } from "../resource/resource-config";
import {  createResourceConfig } from "../resource/resource-config";
import type { WeaponLevelConfig } from "./weapon-level-config";
import {  createWeaponLevelConfig } from "./weapon-level-config";

/**
 * 武器配置
 * @table="map,id"
 * @input="../datas/weapon"
 */
export interface WeaponConfig extends ResourceConfig {
    /**
     * 武器属性
     * @type="map,enums.AttributeType,float"
     */
    readonly attributes: Map<AttributeType, number>;
    /**
     * 武器升级配置列表
     */
    readonly levels: WeaponLevelConfig[];
}

export function createWeaponConfig(_json_: unknown): WeaponConfig {
     const obj = _json_ as Record<string, unknown>;
    return {
        __type__: "weapon.WeaponConfig",
        ...(obj._injectData !== undefined ? { _injectData: obj._injectData } : {}),
        id: obj.id as string,
        name: obj.name as string,
        ...(obj.icon !== undefined ? { icon: obj.icon as string } : {}),
        ...(obj.description !== undefined ? { description: obj.description as string } : {}),
        ...(obj.quality !== undefined ? { quality: obj.quality as unknown as QualityType } : {}),
        attributes: (() => { const _m_ = new Map<AttributeType, number>(); for (const [_k_, _v_] of pairs(obj.attributes as Record<string, defined>)) { _m_.set(tonumber(_k_) as AttributeType, _v_ as number); } return _m_; })(),
        levels: (obj.levels as Array<defined>).map((_item_) => createWeaponLevelConfig(_item_)),
    } as WeaponConfig;
}
