
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



import type { AttributeType } from "../enums/attribute-type";
import {  } from "../enums/attribute-type";

/**
 * 武器升级配置
 */
export interface WeaponLevelConfig {
    /**
     * 武器等级
     * @type="int"
     */
    readonly level: number;
    /**
     * 升到所需矿石
     * @type="int"
     */
    readonly stoneRequired: number;
    /**
     * 升级属性增加百分比(替换)
     * @type="map,enums.AttributeType,float"
     */
    readonly upgradeAttributes: Map<AttributeType, number>;
}

export function createWeaponLevelConfig(_json_: unknown): WeaponLevelConfig {
     const obj = _json_ as Record<string, unknown>;
    return {
        ...(obj._injectData !== undefined ? { _injectData: obj._injectData } : {}),
        level: obj.level as number,
        stoneRequired: obj.stoneRequired as number,
        upgradeAttributes: (() => { const _m_ = new Map<AttributeType, number>(); for (const [_k_, _v_] of pairs(obj.upgradeAttributes as Record<string, defined>)) { _m_.set(tonumber(_k_) as AttributeType, _v_ as number); } return _m_; })(),
    } as WeaponLevelConfig;
}
