use crate::parser::ClassInfo;
use super::to_kebab_case;

pub struct IndexGenerator;

impl IndexGenerator {
    /// Generate index.ts with all registrations and AllTables
    pub fn generate(all_classes: &[ClassInfo], table_classes: &[&ClassInfo]) -> String {
        let mut lines = vec![
            "// Auto-generated by ts-to-luban".to_string(),
            "import { registerCreator, createBean, createByType } from \"./registry\";".to_string(),
            String::new(),
            "// Import all creators".to_string(),
        ];

        // Import creators
        for class in all_classes {
            lines.push(format!(
                "import {{ create{} }} from \"./creators/{}\";",
                class.name, to_kebab_case(&class.name)
            ));
        }

        lines.push(String::new());
        lines.push("// Register all creators".to_string());

        // Register creators
        for class in all_classes {
            lines.push(format!(
                "registerCreator(\"{}\", create{});",
                class.name, class.name
            ));
        }

        lines.push(String::new());
        lines.push("// Import tables".to_string());

        // Import tables
        for class in table_classes {
            let table_name = format!("{}Table", class.name);
            lines.push(format!(
                "import {{ create{}, {} }} from \"./tables/{}\";",
                table_name, table_name, to_kebab_case(&class.name)
            ));
        }

        lines.push(String::new());

        // Generate AllTables interface
        lines.push("export interface AllTables {".to_string());
        for class in table_classes {
            lines.push(format!("    readonly {}Table: {}Table;", class.name, class.name));
        }
        lines.push("}".to_string());
        lines.push(String::new());

        // Generate createAllTables function
        lines.push("export function createAllTables(loader: (file: string) => unknown): AllTables {".to_string());
        lines.push("    return {".to_string());
        for class in table_classes {
            lines.push(format!(
                "        {}Table: create{}Table(loader(\"{}\")),",
                class.name, class.name, to_kebab_case(&class.name)
            ));
        }
        lines.push("    };".to_string());
        lines.push("}".to_string());
        lines.push(String::new());

        // Re-export registry functions
        lines.push("export { createBean, createByType } from \"./registry\";".to_string());

        lines.join("\n")
    }
}
