pub struct RegistryGenerator;

impl RegistryGenerator {
    pub fn generate() -> String {
        r#"// Auto-generated by ts-to-luban
// Bean registry for handling circular dependencies and $type polymorphism

type Creator<T> = (json: unknown) => T;
const beanRegistry = new Map<string, Creator<unknown>>();

export function registerCreator(name: string, creator: Creator<unknown>): void {
    beanRegistry.set(name, creator);
}

export function createBean<T>(name: string, json: unknown): T {
    const creator = beanRegistry.get(name);
    if (!creator) {
        error(`Unknown bean: ${name}`);
    }
    return creator(json) as T;
}

export function createByType<T>(typeName: string, json: unknown): T {
    return createBean<T>(typeName, json);
}
"#.to_string()
    }
}
