use crate::parser::ClassInfo;
use super::to_kebab_case;
use std::path::Path;

pub struct TableGenerator;

impl TableGenerator {
    /// Generate table file content for a @LubanTable class
    pub fn generate(class: &ClassInfo, _output_file: &Path) -> String {
        let config = class.luban_table.as_ref().expect("Class must have @LubanTable");
        let class_name = &class.name;
        let table_name = format!("{}Table", class_name);
        let index_field = &config.index;

        match config.mode.as_str() {
            "map" => Self::generate_map_table(class_name, &table_name, index_field),
            "list" => Self::generate_list_table(class_name, &table_name),
            "one" | "singleton" => Self::generate_one_table(class_name, &table_name),
            _ => panic!("Unknown table mode: {}", config.mode),
        }
    }

    fn generate_map_table(class_name: &str, table_name: &str, index_field: &str) -> String {
        format!(r#"// Auto-generated by ts-to-luban
import {{ createBean }} from "../registry";
import {{ {} }} from "../creators/{}";

export interface {} {{
    readonly dataMap: Map<number, {}>;
    readonly dataList: readonly {}[];
    get(key: number): {} | undefined;
}}

export function create{}(json: unknown): {} {{
    const dataMap = new Map<number, {}>();
    const dataList: {}[] = [];

    for (const [_key, item] of pairs(json as object)) {{
        const obj = createBean<{}>("{}", item);
        dataList.push(obj);
        dataMap.set(obj.{}, obj);
    }}

    return {{
        dataMap,
        dataList,
        get(key: number) {{ return dataMap.get(key); }}
    }};
}}
"#,
            class_name, to_kebab_case(class_name),
            table_name, class_name, class_name, class_name,
            table_name, table_name, class_name, class_name,
            class_name, class_name, index_field
        )
    }

    fn generate_list_table(class_name: &str, table_name: &str) -> String {
        format!(r#"// Auto-generated by ts-to-luban
import {{ createBean }} from "../registry";
import {{ {} }} from "../creators/{}";

export interface {} {{
    readonly dataList: readonly {}[];
}}

export function create{}(json: unknown): {} {{
    const dataList: {}[] = [];
    for (const item of json as defined[]) {{
        dataList.push(createBean<{}>("{}", item));
    }}
    return {{ dataList }};
}}
"#,
            class_name, to_kebab_case(class_name),
            table_name, class_name,
            table_name, table_name, class_name,
            class_name, class_name
        )
    }

    fn generate_one_table(class_name: &str, table_name: &str) -> String {
        format!(r#"// Auto-generated by ts-to-luban
import {{ createBean }} from "../registry";
import {{ {} }} from "../creators/{}";

export interface {} {{
    readonly data: {};
}}

export function create{}(json: unknown): {} {{
    const data = createBean<{}>("{}", json);
    return {{ data }};
}}
"#,
            class_name, to_kebab_case(class_name),
            table_name, class_name,
            table_name, table_name, class_name, class_name
        )
    }
}
